FlightScheduling.Web/Areas/Administration/Models/Instructors/InstructorRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using CsvHelper.Configuration;
using FlightScheduling.DAL;
using FlightScheduling.Language;

namespace FlightScheduling.Web.Areas.Administration.Models.Instructors
{
    public class InstructorRoleViewModel
    {
        //Properties
        public int ID { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "RoleName")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public string Name { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "RequiredHours")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public int? RequiredHours { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "ExpirationDaysRule")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public int? ExpirationDaysRule { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "StartingValidity")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public eStartingValidity StartingValidity { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "StartingRenewal")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public int? StartingRenewal { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "AutomaticRenewal")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public bool AutomaticRenewal { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "IsManager")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public bool IsManager { get; set; }

        [Display(ResourceType = typeof(InstructorsStrings), Name = "AllowChangingRole")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public bool AllowChangingRole { get; set; }
        
        [Display(ResourceType = typeof(InstructorsStrings), Name = "AllowLogin")]
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        public bool AllowLogin { get; set; }


        public string Language { get; set; }

        public bool IsUpdate { get; set; }
        public string ActionResult { get; set; }
    }

    public class InstructorRolesViewModel
    {
        public List<InstructorRoleViewModel> Roles { get; set; }

        public InstructorRolesViewModel()
        {
            this.Roles = new List<InstructorRoleViewModel>();
        }
    }


}

FlightScheduling.Web/Areas/Administration/Models/Instructors/InstructorToOpenUserModel.cs
namespace FlightScheduling.Web.Areas.Administration.Models.Instructors
{
    public class InstructorToOpenUserModel
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string InstructorID { get; set; }
        public string Email { get; set; }
    }
}

FlightScheduling.Web/Areas/Administration/Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Endilo.ExportToExcel;
using Flight.DAL.FlightDB.Methods;
using FlightScheduling.DAL;
using FlightScheduling.DAL.CustomEntities;
using FlightScheduling.Language;
using FlightScheduling.Web.Areas.Administration.Models.Agencies;
using FlightScheduling.Web.Areas.Administration.Models.Common;
using FlightScheduling.Web.Areas.Administration.Models.Instructors;
using FlightScheduling.Web.Infrastructure;
using FlightScheduling.Website.Infrastructure;
using LinqToExcel;
using Otakim.Website.Infrastructure;
using FlightScheduling.DAL.CustomEntities.Permissions;
using Flight.Membership;
using FlightScheduling.DAL.Abstractions;
using FlightScheduling.DAL.DomainEvents;

namespace FlightScheduling.Web.Areas.Administration.Controllers
{
    [Authorize]
    public class InstructorsController : Controller
    {
        private DBRepository _dbDapper = new DBRepository();

        [PermissionAuthorization(PermissionBitEnum.Instructors_Editing)]
        [HttpGet]
        public ActionResult CreateActualUsersForInstructors()
        {
            List<Result<InstructorToOpenUserModel>> results = new List<Result<InstructorToOpenUserModel>>();
            // Get all instructors who are active and has no user
            var instructors = _dbDapper.GetRecords<InstructorToOpenUserModel>(
                QueriesRepository.Instructor.GetAllInstructorsToOpenUsers, new { });

            foreach (var instructor in instructors)
            {
                var instructorCreatedDomainEvent = new InstructorCreatedDomainEvent(instructor.ID);
                var outboxMessage = DomainEventExtensions.GetOutboxFromDomainEvent(instructorCreatedDomainEvent);
                bool outboxResults = _dbDapper.ExecuteCommand(QueriesRepository.Outbox.InsertOutbox, outboxMessage);
                var result = new Result<InstructorToOpenUserModel>();
                result.IsSuccuss = outboxResults;
                result.Value = instructor;
                results.Add(result);
            }

            return View("InstructorToUsers", results);
        }

        [PermissionAuthorization(PermissionBitEnum.Instructors_Viewing)]
        [HttpGet]
        public ActionResult GetInstructors()
        {
            InstructorsViewModel model = new InstructorsViewModel();


            if (FunctionHelpers.User.RoleID == (int)eRole.TrainingManager)
            {
                model.AllowFilterByRole = false;
                model.RoleID = (int)eInstructorRoleType.AccompanyingMentor;
            }

            model.Roles.Items =
                _dbDapper.GetAllInstructorRoles(AppConfig.CurrentLangruageTwoLetters)
                    .Select(r => new CustomSelectListItem()
                    {
                        ID = r.ID,
                        Name = r.Name
                    }).ToList();

            //if (FunctionHelpers.User.RoleID != (int)eRole.TrainingManager)
            //{
            //    model.Instructors =
            //    Mapper.Map<List<Instructors>, List<InstructorViewModel>>(_dbDapper.GetAllInstructors(model.RoleID, null,
            //        null));
            //}

            // Save Instructor state in session
            //Session.Add("InstructorDetailList", model.Instructors);

            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Instructors_Viewing)]
        [HttpPost]
        public ActionResult GetFilteredInstructors(InstructorsViewModel model)
        {
            if (FunctionHelpers.User.RoleID == (int)eRole.TrainingManager)
            {
                model.AllowFilterByRole = false;
                model.RoleID = (int)eInstructorRoleType.AccompanyingMentor;
            }

            model.Roles.Items =
                _dbDapper.GetAllInstructorRoles(AppConfig.CurrentLangruageTwoLetters)
                    .Select(r => new CustomSelectListItem()
                    {
                        ID = r.ID,
                        Name = r.Name
                    }).ToList();

            if (FunctionHelpers.User.RoleID == (int)eRole.TrainingManager)
            {
                if (!String.IsNullOrEmpty(model.InstructorID) || !String.IsNullOrEmpty(model.LastName))
                {
                    model.Instructors =
                        Mapper.Map<List<Instructors>, List<InstructorViewModel>>(_dbDapper.GetAllInstructors(null,
                            model.InstructorID, model.LastName));
                }
            }
            else
            {
                model.Instructors =
                    Mapper.Map<List<Instructors>, List<InstructorViewModel>>(_dbDapper.GetAllInstructors(model.RoleID,
                        model.InstructorID, model.LastName));
            }

            // Save Instructor state in session
            Session.Add("InstructorDetailList", model.Instructors);

            return View("GetInstructors", model);
        }

        [PermissionAuthorization(PermissionBitEnum.Instructors_Viewing)]
        [HttpGet]
        public ActionResult DownloadInstructorList()
        {
            List<InstructorViewModel> _instructors = (List<InstructorViewModel>)Session["InstructorDetailList"];
            ExportToExcel<InstructorViewModel> exc =
                new ExportToExcel<InstructorViewModel>(_instructors, InstructorsStrings.InstructorsReport);
            var stream = exc.GetFile();
            string fileName = String.Format("{0} {1}.xlsx", InstructorsStrings.InstructorsReport,
                DateTime.Now.ToString("dd-MM-yyyy hh:ss"));
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

            stream.Position = 0;
            return File(stream, contentType, fileName);
        }

        [PermissionAuthorization(PermissionBitEnum.Instructors_Editing, PermissionBitEnum.Training_Viewing)]
        [HttpGet]
        public PartialViewResult AddInstructor()
        {
            InstructorViewModel model = new InstructorViewModel();
            model.Roles.Items =
                _dbDapper.GetAllInstructorRoles(AppConfig.CurrentLangruageTwoLetters)
                    .Select(r => new CustomSelectListItem()
                    {
                        ID = r.ID,
                        Name = r.Name
                    }).ToList();
            model.UpdateSensativeData = true;

            return PartialView("_AddInstructor", model);
        }

        [PermissionAuthorization(PermissionBitEnum.Instructors_Editing, PermissionBitEnum.Training_Viewing)]
        [HttpGet]
        public PartialViewResult AddNewInstructor(int TrainingID)
        {
            InstructorViewModel model = new InstructorViewModel();
            model.Roles.Items =
                _dbDapper.GetAllInstructorRoles(AppConfig.CurrentLangruageTwoLetters)
                    .Select(r => new CustomSelectListItem()
                    {
                        ID = r.ID,
                        Name = r.Name
                    }).ToList();
            model.TrainingID = TrainingID;
            model.UpdateSensativeData = true;
            return PartialView("_AddInstructor", model);
        }

        [PermissionAuthorization(PermissionBitEnum.Instructors_Editing, PermissionBitEnum.Training_Viewing)]
        [HttpGet]
        public PartialViewResult UpdateInstructor(int ID)
        {
            InstructorViewModel model = Mapper.Map<Instructors, InstructorViewModel>(_dbDapper.GetInstructor(ID));

            model.UpdateOperation = true;

            //Allowing administrators and Staf to update the Passport and ID
            if (User.IsInRole(eRole.Administrator.ToString()) || User.IsInRole(eRole.Staf.ToString()))
            {
                model.UpdateSensativeData = true;
            }

            return PartialView("_AddInstructor", model);
        }

        [PermissionAuthorization(PermissionBitEnum.Instructors_Editing, PermissionBitEnum.Training_Viewing)]
        [HttpPost]
        public ActionResult AddInstructor(InstructorViewModel model)
        {
            if (ModelState.IsValid)
            {
                Instructors instructor = Mapper.Map<InstructorViewModel, Instructors>(model);

                Trainings training = new Trainings();
                if (model.TrainingID != null)
                {
                    training = _dbDapper.GetTraining((int)model.TrainingID);
                    instructor.RoleID = training.RoleID;
                }


                instructor.UpdateDate = DateTime.Now;
                instructor.UserID = FunctionHelpers.User.UserID;


                if (model.UpdateOperation)
                {
                    _dbDapper.UpdateInstructor(instructor);
                }
                else
                {
                    if (model.TrainingID != null)
                    {
                        bool updatingExistingInstructor = false;
                        if (_dbDapper.CheckInstructorExistByInstructorID(model.InstructorID))
                        {
                            Instructors _existInstructor = _dbDapper.GetInstructorByInstructorID(model.InstructorID);

                            if (_existInstructor.InstructorRoles.AllowChangingRole)
                            {
                                instructor.ID = _existInstructor.ID;
                                instructor.ValidityStartDate = null;
                                instructor.ValidityEndTime = null;

                                updatingExistingInstructor = true;
                            }
                            else
                            {
                                //TODO: returing a message that istructor is already exist in the sytem and it can't be added
                                return RedirectToAction("TrainingFolder", new { ID = model.TrainingID });
                            }

FlightScheduling.Web/Areas/Administration/Views/Instructors/GetTrainings.cshtml
@using FlightScheduling.Language
@using FlightScheduling.Web.Infrastructure
@using Flight.DAL.FlightDB.Methods
@using FlightScheduling.DAL.CustomEntities.Permissions
@using FlightScheduling.Web.App_Start
@model FlightScheduling.Web.Areas.Administration.Models.Instructors.TrainingsViewModel

@{
    /**/

    /**/

    ViewBag.Title = InstructorsStrings.TrainingsManagement;
    Layout = "~/Views/Shared/_InstructorManagementMenu.cshtml";
}

@section styles
{
    @Styles.Render("~/Content/css/datepicker")
    @Styles.Render("~/bundles/css/chosen")
}

<h2>@InstructorsStrings.TrainingsManagement</h2>

@using (Html.BeginForm("GetTrainings", "Instructors", FormMethod.Post))
{
    @*<h5 class="filters-header">סינון נתונים</h5>*@
    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.RoleID, new { @class = "control-label" })
        @Html.DropDownListFor(model => model.RoleID, new SelectList(Model.Roles.Items, "ID", "Name"), CommonStrings.ShowAll, new { @class = "control-label chosen-select chosen-rtl" })
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.FilterFromDate, new { @class = "control-label " })
        @Html.TextBoxFor(model => model.FilterFromDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", @value = @DateTime.Now })
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.FilterToDate, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.FilterToDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", @value = @DateTime.Now })
    </div>

    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.TrainingLocation, new { @class = "control-label" })
        @Html.EnumDropDownListFor(m => m.TrainingLocation, CommonStrings.ShowAll, new { @class = "control-label chosen-select chosen-rtl" })
    </div>
    if (!User.IsInRole(eRole.TrainingManager.ToString()))
    {
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Region, new { @class = "control-label" })
            @Html.EnumDropDownListFor(m => m.Region, CommonStrings.ShowAll, new { @class = "control-label chosen-select chosen-rtl" })
        </div>
    }
    else
    {
        @Html.HiddenFor(m => m.Region)
    }
    <div class="form-group col-md-4">
        @Html.LabelFor(model => model.TrainingTypeID, new { @class = "control-label" })
        @Html.DropDownListFor(model => model.TrainingTypeID, new SelectList(Model.TrainingTypes.Items, "ID", "Name"), CommonStrings.ShowAll, new { @class = "control-label chosen-select chosen-rtl" })
    </div>

    <div class="form-group col-md-4 checkbox-form">
        @Html.CheckBoxFor(m => m.CompletedTraining, new { @class = "form-control form-checkbox" })
        @Html.LabelFor(m => m.CompletedTraining)
    </div>

    <div class="col-md-1 pull-left margin-top-20px">
        <input type="submit" value="@CommonStrings.Search" class="btn btn-default" />
    </div>
    <hr class="light-seperator" />
}

@if (PermissionLoader.CheckUserPermissions(PermissionBitEnum.Training_Editing))
{
    @(Ajax.LinkForBootstrapModal("AddTraining", "Instructors", null)
    .HtmlAttributes(new { @class = "btn btn-primary btn-sm pull-left form-validation", id = "trainignsAddAddTraining", title = InstructorsStrings.AddTraining })
    .RawLabel(@<text>@InstructorsStrings.AddTraining</text>)
    .LoadingPanelID("TrainingsLoadingPanelContainer")
    .ModalWindowContainerID("TrainingsModalWindowContainer")
    .UseExsistingModalcontainer(true)
    )
}
@Html.Grid(Model.Trainings).Columns(col =>
{
    col.For(c => @Html.GetLinkWithHtml(Html.GetIcon(Icons.Folder, InstructorsStrings.TrainingFolder).ToString(), "TrainingFolder", "Instructors", new { ID = c.ID }, null)).Named(InstructorsStrings.TrainingFolder).Encode(false);
    col.For(c => c.Name).Named(InstructorsStrings.TrainingName);
    col.For(c => c.TrainingRegion != null ? c.TrainingRegion.GetDescription() : null).Named(SchoolsStrings.Region);
    col.For(c => c.TrainingDate).Named(InstructorsStrings.TrainingDate).Format(AppConfig.FormatDateGrid);
    col.For(c => c.TrainingLocation.GetDescription()).Named(InstructorsStrings.TrainingLocation);
    col.For(c => c.TrainingHours).Named(InstructorsStrings.TrainingHours);
    col.For(c => c.InstructorRole.Name).Named(InstructorsStrings.RoleName);
    col.For(c => c.TrainingType.GetDescription()).Named(InstructorsStrings.ValidationType);
    col.For(c => Html.GetIcon(c.IsCompleted ? Icons.Ok : Icons.No, null)).Named(InstructorsStrings.IsCompleted);
    col.For(c => @Ajax.LinkForBootstrapModalNo("UpdateTraining", "Instructors", Html.GetIcon(Icons.Edit, null).ToString(), new { @ID = c.ID }, new { @class = "lable lable-default", title = CommonStrings.Update })).Named(CommonStrings.Update).Encode(false).CellCondition(x => PermissionLoader.CheckUserPermissions(PermissionBitEnum.Training_Editing));
    col.For(c => @Ajax.LinkForBootstrapModalNo("DeleteTraining", "Instructors", Html.GetIcon(Icons.Delete, null).ToString(), new { @ID = c.ID, @Title = c.Name }, new { @class = "lable lable-default", title = CommonStrings.Delete })).Named(CommonStrings.Delete).Encode(false).CellCondition(x => PermissionLoader.CheckUserPermissions(PermissionBitEnum.Training_Deleting));
}).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "trainingsList").Empty(CommonStrings.Empty)


<div id="TrainingsModalWindowContainer" class="modal fade"></div>
<div id="TrainingsLoadingPanelContainer" class="modal-loading-panel" style="display: none"></div>

@section scripts
{

    @Scripts.Render("~/bundles/datepicker");
    @Scripts.Render("~/bundles/chosen")

}

FlightScheduling.Web/Areas/Administration/Views/Instructors/TrainingFolder.cshtml
@using Flight.DAL.FlightDB.Methods
@using FlightScheduling.DAL
@using FlightScheduling.Language
@using FlightScheduling.DAL.CustomEntities.Permissions
@using FlightScheduling.Web.App_Start
@model FlightScheduling.Web.Areas.Administration.Models.Instructors.TrainingFolderViewModel

@{
    ViewBag.Title = InstructorsStrings.TrainingFolder;
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

@section styles
{
    @Styles.Render("~/Content/css/datepicker")
    @Styles.Render("~/bundles/css/chosen")
}
<h2>@InstructorsStrings.TrainingFolder</h2>
<div class="innerTripDetails">
    <div class="row section">
        <div class="col-lg-6">
            @Html.Partial("_TrainingDetails", Model.TrainingDetails)
        </div>
        <div class="col-lg-6">
            @Html.Partial("_InstructorRoleDetails", Model.TrainingDetails.InstructorRole)
        </div>
    </div>

    @if (!Model.TrainingDetails.IsCompleted && Model.TrainingDetails.TrainingType == eTrainingType.RenewalTraining && PermissionLoader.CheckUserPermissions(PermissionBitEnum.Instructors_Editing))
    {
        <div class="row section">
            <div class="col-lg-12">
                @using (Html.BeginForm("RegisterInstructor", "Instructors", FormMethod.Post))
                {
                    @Html.HiddenFor(m => m.InstructorRegistrationToTraining.TrainingID)
                    <div class="form-group">
                        @Html.LabelFor(model => model.InstructorRegistrationToTraining.InstructorsRegistration, new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.InstructorRegistrationToTraining.InstructorID, new SelectList(Model.InstructorRegistrationToTraining.InstructorsRegistration.Items, "ID", "Name"), CommonStrings.SelectValue, new { @class = "form-control chosen-select chosen-rtl" })
                        </div>
                    </div>
                    <input type="submit" id="btnSubmit" value="@CommonStrings.Save" class="btn btn-default" />
                }
            </div>
        </div>
    }
    <div class="row selction">
        <div class="col-lg-12">
            <div class="btn-group pull-left">

                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @CommonStrings.Actions <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    @if (!Model.TrainingDetails.IsCompleted && PermissionLoader.CheckUserPermissions(PermissionBitEnum.Training_ClosingTraining))
                    {
                        <li>
                            @(Ajax.LinkForBootstrapModal("CompleteTraining", "Instructors", routeValues: new { ID = Model.TrainingDetails.ID })
                                    .HtmlAttributes(new { @class = "form-validation", id = "CompleteTraining", title = InstructorsStrings.CompleteTraining })
                                    .RawLabel(@<text>@InstructorsStrings.CompleteTraining</text>)
                        .LoadingPanelID("TrainingFolderLoadingPanelContainer")
                        .ModalWindowContainerID("TrainingFolderModalWindowContainer")
                        .UseExsistingModalcontainer(true)
                            )
                        </li>
                    }
                    @if (!Model.TrainingDetails.IsCompleted && PermissionLoader.CheckUserPermissions(PermissionBitEnum.Training_UpdateInstructorCertificate))
                    {
                        <li>
                            @(Ajax.LinkForBootstrapModal("UpdateInstructorsExpirationDates", "Instructors", routeValues: new { TrainingID = Model.TrainingDetails.ID })
                            .HtmlAttributes(new { @class = "form-validation", id = "UpdateInstructorsTrainingExpiration", title = InstructorsStrings.UpdateInstructorExpiration })
                            .RawLabel(@<text>@InstructorsStrings.UpdateInstructorExpiration</text>)
                            .LoadingPanelID("TrainingFolderLoadingPanelContainer")
                            .ModalWindowContainerID("TrainingFolderModalWindowContainer")
                            .UseExsistingModalcontainer(true)
                            )
                        </li>
                    }

                    @if (Model.TrainingDetails.TrainingType == eTrainingType.InitialTraining && PermissionLoader.CheckUserPermissions(PermissionBitEnum.Instructors_Editing))
                    {
                        <li>
                            @(Ajax.LinkForBootstrapModal("AddNewInstructor", "Instructors", routeValues: new { TrainingID = Model.TrainingDetails.ID })
                                                                                  .HtmlAttributes(new { @class = "form-validation", id = "AddInstructor", title = InstructorsStrings.AddInstructor })
                                                                                  .RawLabel(@<text>@InstructorsStrings.AddInstructor</text>)
.LoadingPanelID("TrainingFolderLoadingPanelContainer")
.ModalWindowContainerID("TrainingFolderModalWindowContainer")
.UseExsistingModalcontainer(true)
                            )
                        </li>
                        <li>
                            @(Ajax.LinkForBootstrapModal("ImportNewInstructors", "Instructors", routeValues: new { TrainingID = Model.TrainingDetails.ID })
                                                                                  .HtmlAttributes(new { @class = "form-validation", id = "ImportNewInstructors", title = InstructorsStrings.ImportNewInstructors })
                                                                                  .RawLabel(@<text>@InstructorsStrings.ImportNewInstructors</text>)
.LoadingPanelID("TrainingFolderLoadingPanelContainer")
.ModalWindowContainerID("TrainingFolderModalWindowContainer")
.UseExsistingModalcontainer(true)
                            )
                        </li>
                    }
                </ul>
            </div>

            @Html.Partial("_InstructorsList", Model.Instructors)
        </div>
    </div>
</div>

<div id="TrainingFolderModalWindowContainer" class="modal fade"></div>
<div id="TrainingFolderLoadingPanelContainer" class="modal-loading-panel" style="display:none"></div>



@section scripts
{

    @Scripts.Render("~/bundles/datepicker")
    @Scripts.Render("~/bundles/chosen")

}

FlightScheduling.Web/Areas/Administration/Views/Instructors/_CompleteTraining.cshtml
@using FlightScheduling.Language
@model FlightScheduling.Web.Areas.Administration.Models.Instructors.CompleteTrainingViewModel



@using (Html.BeginForm("CompleteTraining", "Instructors", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-validation", id = "form-add-note" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.TrainingID)

    <div class="modal-dialog modal-lg" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>
                   @InstructorsStrings.CompleteTraining
                </h4>
            </div>
            <div class="modal-body">
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        @InstructorsStrings.CompleteTrainingInstructions
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default validate-form">
                    <span class="button-text">@InstructorsStrings.ReportCompletion</span>
                    <div class="white-v"></div>
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">@CommonStrings.Close</button>

            </div>
        </div>
    </div>
}

<script type="text/javascript" src="~/Scripts/Common/validate.form.custom.methods.js"></script>

FlightScheduling.Web/Areas/Administration/Views/Instructors/_InstructorFolderFiles.cshtml
@using Flight.DAL.FlightDB.Methods
@using FlightScheduling.Language
@using FlightScheduling.DAL.CustomEntities.Permissions
@using FlightScheduling.Web.App_Start
@model IEnumerable<FlightScheduling.Web.Areas.Administration.Models.Instructors.InstructorFileViewModel>



@Html.Grid(Model).Columns(col =>
{
    col.For(c => @Html.ActionLink(c.Name, "DownloadFile", "Instructors", new {@InstructorID = c.InstructorID, @FilePath = c.Url, @FileName = c.Name }, null)).Named(GroupsStrings.FileName);
    col.For(c => c.CreationDate).Named(CommonStrings.CreationDate).Format("{0:dd/MM/yyyy hh:mm:ss}");
    col.For(c => c.Comments).Named(GroupsStrings.FileComments);
    col.For(c => @Ajax.LinkForBootstrapModalNo("UpdateFile", "Instructors", Html.GetIcon(Icons.Edit, null).ToString(), new { @ID = c.ID }, new { @class = "lable lable-default", title = CommonStrings.Update })).Named(CommonStrings.Update).Encode(false).CellCondition(x => PermissionLoader.CheckUserPermissions(PermissionBitEnum.Instructors_Files_Editing));
    col.For(c => @Ajax.LinkForBootstrapModalNo("DeleteFile", "Instructors", Html.GetIcon(Icons.Delete, null).ToString(), new { @ID = c.ID, @fileName = c.Name }, new { @class = "lable lable-default", title = CommonStrings.Delete })).Named(CommonStrings.Delete).Encode(false).CellCondition(x => PermissionLoader.CheckUserPermissions(PermissionBitEnum.Instructors_Files_Deleting));
}).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "InstructorsFilesList").Empty(CommonStrings.Empty)