FlightScheduling.Web/Areas/Administration/Models/Users/UsersViewModels.cs
using FlightScheduling.Language;
using FlightScheduling.Web.Areas.Administration.Models.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.AccessControl;
using System.Web;

namespace FlightScheduling.Web.Areas.Administration.Models.Users
{
    public class UserViewModel
    {
        //Properties

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }

    }

    public class UpdateUserPermissionRoleViewModel
    {
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(PermissionStrings), Name = "RoleName")]
        public CustomSelectList Roles { get; set; }
        public List<int> SelectedUsers { get; set; }
        public int RoleID { get; set; }

        public UpdateUserPermissionRoleViewModel()
        {
            Roles = new CustomSelectList();
        }
    }

    public class UpdateUsersAccessToSystem
    {
        public List<int> SelectedUsers { get; set; }

        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(SchoolsStrings), Name = "IsActive")]
        public CustomSelectList AccessList { get; set; }

        public int SelectedAccess { get; set; }

        public UpdateUsersAccessToSystem()
        {
            AccessList = new CustomSelectList();
            AccessList.Items = new List<CustomSelectListItem>();
            AccessList.Items.Add(new CustomSelectListItem()
            {
                ID = 0,
                Name = CommonStrings.AccessDenied
            });
            AccessList.Items.Add(new CustomSelectListItem()
            {
                ID = 1,
                Name = CommonStrings.AccessAllowed
            });
        }
    }

}

FlightScheduling.Web/Areas/Administration/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Flight.DAL.FlightDB.Methods;
using Flight.Membership;
using FlightScheduling.DAL;
using FlightScheduling.Language;
using FlightScheduling.Web.Areas.Administration.Models;
using FlightScheduling.Web.Areas.Administration.Models.Users;
using FlightScheduling.Website.Models.Account;
using Otakim.Website.Infrastructure;
using FlightScheduling.Web.Areas.Administration.Models.Schools;
using FlightScheduling.Web.Areas.Administration.Models.Common;
using FlightScheduling.Web.Areas.Administration.Models.Administration;
using FlightScheduling.DAL.CustomEntities.Notifications;
using Endilo.Emails;
using System.Net.Mail;

namespace FlightScheduling.Web.Areas.Administration.Controllers
{
    [EndiloAuthorization(eRole.Administrator)]
    public class UsersController : Controller
    {
        private FlightDB _db = new FlightDB();
        DBRepository _dbDapper = new DBRepository();

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
        //
        // GET: /Administration/Users/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetUsers(int? PageNumber = 1, int? NumberOfRows = 20)
        {
            UsersViewModel model = new UsersViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult GetUsers(UsersViewModel model)
        {
            if (model.Roles != null)
            {
                model.RoleID = (int)model.Roles;
            }
            model.ShowDeletedUsers = !model.ShowDeletedUsers;

            model.UserModels = _dbDapper.GetRecords<UserModel>(QueriesRepository.GetAllUsers, new
            {
                model.RoleID,
                model.Email,
                model.Name,
                model.ShowDeletedUsers,
                model.SelectedActivation
            }).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int UserID)
        {
            //Users user = _db.Users.FirstOrDefault(u => u.ID.Equals(UserID));
            Users user = _dbDapper.GetUserByID(UserID);

            switch (user.RuleEnum)
            {
                case eRole.Agent:
                    {
                        return RedirectToAction("EditAgent", new { ID = user.ID });
                        break;
                    }
                case eRole.Staf:
                    {
                        return RedirectToAction("EditStaf", new { ID = user.ID });
                        break;
                    }
                case eRole.Administrator:
                case eRole.Viewer:
                case eRole.GroupManager:
                    {
                        return RedirectToAction("EditUser", new { ID = user.ID });
                        break;
                    }
                case eRole.SchoolManager:
                    {
                        return RedirectToAction("EditSchoolUser", new { ID = user.ID });
                        break;
                    }
                case eRole.TrainingManager:
                    {
                        return RedirectToAction("EditTrainingManager", new { ID = user.ID });
                        break;
                    }
                case eRole.CountyManager:
                    {
                        return RedirectToAction("EditCountyManager", new { ID = user.ID });
                        break;
                    }

            }

            return null;
        }

        [HttpGet]
        public ActionResult AddAgent()
        {
            AgentViewModel model = new AgentViewModel();
            model.AgenciesModel.AddRange(_db.Agencies.Select(a => new AgencyViewModelBasic()
            {
                ID = a.ID,
                Name = a.Name
            }).ToList());

            model.LoadPermissionRoles();

            return View(model);
        }

        public ActionResult AddAgent(AgentViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Check if user exsist and retun false
                if (_db.CheckIfUsersExists(model.Email))
                {
                    ModelState.AddModelError("UsersExsits", ValidationStrings.UserExistWithEmail);
                    return View(model);
                }

                Users _userToAdd = new Users();
                _userToAdd.RuleEnum = eRole.Agent;
                _userToAdd.UserType = (int)eRole.Agent;
                _userToAdd.CreationDate = DateTime.Now;
                _userToAdd.Firstname = model.FirstName;
                _userToAdd.Lastname = model.LastName;
                if (model.AgencyID == -1)
                {
                    //TODO: Validation
                }
                _userToAdd.AgencyID = model.AgencyID;
                _userToAdd.IsActive = true;
                _userToAdd.Password = model.Password;
                _userToAdd.Phone = model.Phone;
                _userToAdd.Email = model.Email;

                FlightMembershipProvider membership = new FlightMembershipProvider();

                _userToAdd = membership.CreateUser(_userToAdd);


                return RedirectToAction("GetUsers");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult EditAgent(int ID)
        {
            //Users user = _db.Users.FirstOrDefault(u => u.ID.Equals(ID));
            Users user = _dbDapper.GetUserByID(ID);

            AgentViewModel model = new AgentViewModel();

            model.UserID = user.ID;
            model.CreationDate = user.CreationDate;
            model.Email = user.Email;
            model.FirstName = user.Firstname;
            model.LastName = user.Lastname;
            model.Phone = user.Phone;
            model.Role = user.RuleEnum;
            model.AgencyID = (int)user.AgencyID;

            model.AgenciesModel.AddRange(_db.Agencies.Select(a => new AgencyViewModelBasic()
            {
                ID = a.ID,
                Name = a.Name
            }).ToList());

            return View(model);
        }

        [HttpPost]
        public ActionResult EditAgent(AgentViewModel model)
        {
            ModelState.Remove("Email");
            if (ModelState.IsValid)
            {



                Users user = _db.Users.FirstOrDefault(u => u.ID.Equals(model.UserID));

                if (!String.IsNullOrEmpty(model.Email) && model.Email != user.Email)
                {
                    if (_db.CheckIfUsersExists(model.Email))
                    {
                        ModelState.AddModelError("UsersExsits", ValidationStrings.UserExistWithEmail);
                        return View(model);
                    }
                }

                user.AgencyID = model.AgencyID;
                //user.Email = model.Email;
                user.Firstname = model.FirstName;
                user.Lastname = model.LastName;
                user.Password = model.Password;
                user.Phone = model.Phone;
                user.UserType = (int)model.Role;
                user.Email = model.Email;

                FlightMembershipProvider membership = new FlightMembershipProvider();
                membership.UpdateUser(user);

                return RedirectToAction("GetUsers");
            }

            return View(model);
        }


        [HttpGet]
        public ActionResult AddStaf()
        {

            StafViewModel model = new StafViewModel();
            model.LoadPermissionRoles();

            return View(model);
        }

        [HttpPost]
        public ActionResult AddStaf(StafViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Check if user exsist and retun false
                if (_db.CheckIfUsersExists(model.Email))
                {
                    ModelState.AddModelError("UsersExsits", ValidationStrings.UserExistWithEmail);
                    return View(model);
                }

                Users _userToAdd = new Users();
                _userToAdd.RuleEnum = eRole.Staf;
                _userToAdd.UserType = (int)eRole.Staf;
                _userToAdd.CreationDate = DateTime.Now;
                _userToAdd.Firstname = model.FirstName;
                _userToAdd.Lastname = model.LastName;
                _userToAdd.IsActive = true;
                _userToAdd.Password = model.Password;
                _userToAdd.Phone = model.Phone;
                _userToAdd.Email = model.Email;
                _userToAdd.RoleTypeEnum = model.RoleType;
                _userToAdd.PermissionRoleID = model.PermissionRoleID;

                FlightMembershipProvider membership = new FlightMembershipProvider();

                _userToAdd = membership.CreateUser(_userToAdd);

                return RedirectToAction("GetUsers");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult AddTrainingManager()
        {

            TrainingManagerViewModel model = new TrainingManagerViewModel();
            model.LoadPermissionRoles();

            return View(model);
        }

        [HttpPost]
        public ActionResult AddTrainingManager(TrainingManagerViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Check if user exsist and retun false
                if (_db.CheckIfUsersExists(model.Email))
                {
                    ModelState.AddModelError("UsersExsits", ValidationStrings.UserExistWithEmail);
                    return View(model);
                }

                Users _userToAdd = new Users();
                _userToAdd.RuleEnum = eRole.TrainingManager;
                _userToAdd.UserType = (int)eRole.TrainingManager;

FlightScheduling.Web/Areas/Administration/Views/Users/AddAgent.cshtml
@using FlightScheduling.Language
@model FlightScheduling.Web.Areas.Administration.Models.AgentViewModel

@{
    ViewBag.Title = "AddAgent";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}
@section styles
{
    @Styles.Render("~/bundles/css/chosen")
}

<h2>@AdministrationStrings.AddAgent</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-lg-10 col-md-8 col-sm-6">
        <div class="form-horizontal">


            @Html.ValidationSummary(true)
            @Html.HiddenFor(m => m.Role)

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email)
                    @Html.ValidationMessage("UsersExsits")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AgencyID, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.AgencyID, new SelectList(Model.AgenciesModel, "ID", "Name"), new { @class = "form-control chosen-select chosen-rtl" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Phone)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PermissionRoles, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.PermissionRoleID, new SelectList(Model.PermissionRoles.Items, "ID", "Name"), CommonStrings.SelectValue, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PermissionRoles)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    <input type="submit" value="@CommonStrings.Add" class="btn btn-primary pull-left" />
                </div>
            </div>

        </div>
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/chosen")
}

FlightScheduling.Web/Areas/Administration/Views/Users/AddCountyManager.cshtml
@using FlightScheduling.Language
@model FlightScheduling.Web.Areas.Administration.Models.CountyManagerViewModel

@{
    ViewBag.Title = AdministrationStrings.AddCountyManager;
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>@AdministrationStrings.AddCountyManager</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-lg-10 col-md-8 col-sm-6">
        <div class="form-horizontal">


            @Html.ValidationSummary(true)
            @Html.HiddenFor(m => m.Role)

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email)
                    @Html.ValidationMessage("UsersExsits")
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Phone)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Region, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EnumDropDownListFor(model => model.Region, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Region)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PermissionRoles, new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.PermissionRoleID, new SelectList(Model.PermissionRoles.Items, "ID", "Name"), CommonStrings.SelectValue, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PermissionRoles)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    <input type="submit" value="@CommonStrings.Add" class="btn btn-primary pull-left" />
                </div>
            </div>

        </div>
    </div>
}

FlightScheduling.Web/Areas/Administration/Views/Users/GetUsers.cshtml
@using Endilo.Helpers
@using FlightScheduling.Language
@using MvcContrib.UI.Grid
@model FlightScheduling.Web.Areas.Administration.Models.UsersViewModel

@{
    ViewBag.Title = AdministrationStrings.Users;
    Layout = "~/Views/Shared/_SystemAdministration.cshtml";
}

@section styles
{
    @Styles.Render("~/Content/css/datepicker")
    @Styles.Render("~/bundles/css/chosen")
    @Styles.Render("~/Content/css/jQueryUI")
}

<h2>@AdministrationStrings.Users</h2>
@using (Html.BeginForm("GetUsers", "Users", FormMethod.Post))
{
    <div class="row">
        <div class="form-group col-md-4" id="filter-OrderStatus">
            @Html.LabelFor(model => model.Roles, null, new { @class = "control-label" })
                @Html.EnumDropDownListFor(model => model.Roles, CommonStrings.SelectValue, new { @class = "form-control chosen-select chosen-rtl" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Activation, null, new { @class = "control-label" })
                @Html.ListBoxFor(m => m.SelectedActivation, new MultiSelectList(Model.Activation.Items, "ID", "Name"), new { @class = "form-control chosen-select chosen-rtl" })
        </div>

        <div class="form-group col-md-4 checkbox-form">
            @Html.CheckBoxFor(m => m.ShowDeletedUsers, new { @class = "form-control form-checkbox" })
            @Html.LabelFor(model => model.ShowDeletedUsers, new { @class = "control-label" })
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="@CommonStrings.Search" class="btn btn-default pull-left" />
            </div>
        </div>
    </div>
    <div>&nbsp;</div>
    <hr class="light-seperator" />
}
<div class="row">
    <div class="btn-group pull-left">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @CommonStrings.Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li class="multi-action disabled">
                <a href="#" id="update-permission-role" data-container="UsersModalWindowContainer" data-action="@Url.Action("UpdateUserPermissionsRole","Users")">@PermissionStrings.UpdateUserRole</a>
            </li>
            <li class="multi-action disabled">
                <a href="#" id="update-access-toSystem" data-container="UsersModalWindowContainer" data-action="@Url.Action("UpdateUsersAccessToSystem","Users")">@AccountStrings.UpdateAccessToSystem</a>
            </li>
            <li class="multi-action disabled">
                <a href="#" id="compose-global-notification" data-container="UsersModalWindowContainer" data-action="@Url.Action("ComposeGlobalNotification","Users")">@NotificationStrings.SendMessage</a>
            </li>
        </ul>
    </div>


    <div class="col-12">
        <!-- Single button -->
        <div class="btn-group">
            <button type="button" class="btn btn-primary btn-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                @AdministrationStrings.AddUser <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="/Administration/Users/AddAdministrator">@AdministrationStrings.AddAdministrator</a></li>
                <li><a href="/Administration/Users/AddAgent">@AdministrationStrings.AddAgent</a></li>
                <li><a href="/Administration/Users/AddStaf">@AdministrationStrings.AddStaf</a></li>
                <li><a href="/Administration/Users/AddViewerUser">@AdministrationStrings.AddViewer</a></li>
                <li><a href="/Administration/Users/AddTrainingManager">@AdministrationStrings.AddTrainingManager</a></li>
                <li><a href="/Administration/Users/AddCountyManager">@AdministrationStrings.AddCountyManager</a></li>
            </ul>
        </div>
    </div>
</div>
@if (!Model.ShowDeletedUsers)
{
    @Html.Grid(Model.UserModels).Columns(col =>
{
    col.For(c => c.UserID).Named(AccountStrings.UserID);
    col.For(c => String.Format("{0} {1}", c.FirstName, c.LastName)).Named(AccountStrings.FullName);
    col.For(c => c.Email).Named(AccountStrings.EmailAddress);
    col.For(c => c.Role != null ? c.Role.GetDescription() : "").Named(AccountStrings.Role);
    col.For(c => c.Phone).Named(AccountStrings.Phone);
    col.For(c => c.CreationDate.ToString("dd/MM/yyyy")).Named(AccountStrings.CreationDate);
    col.For(c => @Html.GetLinkWithHtml(@Html.GetIcon(Icons.Restore, null).ToString(), "RestoreUser", "Users", new { UserID = c.UserID }, null)).Named(CommonStrings.Restore);
}).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "userManagement").Empty(CommonStrings.Empty)
}
else
{
    @Html.Grid(Model.UserModels).Columns(col =>
{
    col.For(c => Html.CheckBox(c.UserID.ToString(), false, new { ID = c.UserID, @class = "form-control form-checkbox table-checkbox tcheck" }).ToString()).Named("").Header("<th><input type=\"checkbox\" class=\"form-control form-checkbox table-checkbox\" id='chkHeader' /></th>").Sortable(false).Encode(false).HeaderAttributes(new Dictionary<string, object> { { "style", "width:20px" } });
    col.For(c => c.UserID).Named(AccountStrings.UserID);
    col.For(c => String.Format("{0} {1}", c.FirstName, c.LastName)).Named(AccountStrings.FullName);
    col.For(c => c.Email).Named(AccountStrings.EmailAddress);
    col.For(c => c.Role != null ? c.Role.GetDescription() : "").Named(AccountStrings.Role);
    col.For(c => c.Phone).Named(AccountStrings.Phone);
    col.For(c => c.PermissionRoleName).Named(PermissionStrings.RoleName);
    col.For(c => @Html.GetLable(c.IsActivate, c.IsActivate ? CommonStrings.AccessAllowed : CommonStrings.AccessDenied)).Named(SchoolsStrings.IsActive);
    col.For(c => c.CreationDate.ToString("dd/MM/yyyy")).Named(AccountStrings.CreationDate);
    col.For(c => @Html.GetLinkWithHtml(@Html.GetIcon(Icons.Edit, null).ToString(), "Edit", "Users", new { UserID = c.UserID }, null)).Named(CommonStrings.Edit);
    col.For(c => @Ajax.LinkForBootstrapModalNo("DeleteUserConfirm", "Users", Html.GetIcon(Icons.Delete, null).ToString(), new { @ID = c.UserID }, new { @class = "lable lable-default", title = FlightsStrings.LinkFlight })).Named(CommonStrings.Delete).Encode(false);
}).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "userManagement").Empty(CommonStrings.Empty)

}



<div id="UsersModalWindowContainer" class="modal fade"></div>
<div id="UsersLoadingPanelContainer" class="modal-loading-panel" style="display:none"></div>
@section scripts
{
    @Scripts.Render("~/bundles/datepicker")
    @Scripts.Render("~/bundles/chosen")
    @Scripts.Render("~/bundles/jQueryUI")
}

FlightScheduling.Web/Areas/Administration/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}

<h2>Index</h2>

FlightScheduling.Web/Areas/Administration/Views/Users/_UpdateUserAccessToSystem.cshtml
@using Flight.DAL.FlightDB.Methods
@using FlightScheduling.Language
@model FlightScheduling.Web.Areas.Administration.Models.Users.UpdateUsersAccessToSystem

@using (Html.BeginForm("ChangeUsersAccessToSystem", "Users", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-validation", id = "form-associate-school" }))
{
    @Html.AntiForgeryToken()
    for (int i = 0; i < Model.SelectedUsers.Count(); i++)
    {
        @Html.HiddenFor(m => m.SelectedUsers[i])
    }


    <div class="modal-dialog modal-lg" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>@AccountStrings.UpdateAccessToSystem</h4>
            </div>
            <div class="modal-body">
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-lg-10 col-md-8 col-sm-6">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)

                            <div class="form-group">
                                @Html.LabelFor(model => model.AccessList, new { @class = "control-label" })
                                @Html.DropDownListFor(model => model.SelectedAccess, new SelectList(Model.AccessList.Items, "ID", "Name"),CommonStrings.SelectValue, new { @class = "form-control chosen-select chosen-rtl" })
                                @Html.ValidationMessageFor(model => model.AccessList)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default validate-form">
                    <span class="button-text">@CommonStrings.SaveAndClose</span>
                    <div class="white-v"></div>
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">@CommonStrings.Close</button>

            </div>
        </div>
    </div>
}

<script type="text/javascript" src="~/Scripts/Common/validate.form.custom.methods.js"></script>
<script type="text/javascript" src="~/Scripts/chosen/chosen-methods.ajax.js"></script>