FlightScheduling.Web/Areas/Administration/Models/Reports/AgencyReportViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Endilo.ExportToExcel;
using FlightScheduling.DAL;
using FlightScheduling.Language;
using Otakim.Language;

namespace FlightScheduling.Web.Areas.Administration.Models.Reports
{
    public class AgencyReportContainerViewModel
    {
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(CommonStrings), Name = "FromDate")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(CommonStrings), Name = "To")]
        public DateTime EndDate { get; set; }

        public List<AgencyReportViewModel> Data { get; set; }

        public AgencyReportContainerViewModel()
        {
            StartDate = new DateTime(DateTime.Now.Year, 1, 1);
            EndDate = new DateTime(DateTime.Now.Year, 12, 31);
            Data = new List<AgencyReportViewModel>();
        }
    }


    public class AgencyReportViewModel
    {
        [ExportToExcel(ResourceType = typeof(SchoolsStrings), HeaderName = "ID")]
        public int SchoolID { get; set; }

        [ExportToExcel(ResourceType = typeof(SchoolsStrings), HeaderName = "InstituteID")]
        public int InstituteID { get; set; }

        [ExportToExcel(ResourceType = typeof(SchoolsStrings), HeaderName = "Name")]
        public string SchoolName { get; set;}

        public int RegionID { get; set; }

        [ExportToExcel(ResourceType = typeof(SchoolsStrings), HeaderName = "Region")]
        [Display(ResourceType = typeof(SchoolsStrings), Name = "Region")]
        public string Region => ((eSchoolRegion)RegionID).GetEnumDescription();

        [ExportToExcel(ResourceType = typeof(TripsStrings), HeaderName = "DepartureDate")]
        public DateTime DepartureDate { get; set; }

        [ExportToExcel(ResourceType = typeof(TripsStrings), HeaderName = "ReturnDate")]
        public DateTime ReturnDate { get; set; }

        [ExportToExcel(ResourceType = typeof(TripsStrings), HeaderName = "Destenation")]
        public string Destenation => ((eFlightsFields) this.DestinationID).GetDescription();

        public int DestinationID { get; set; }

        [ExportToExcel(ResourceType = typeof(TripsStrings), HeaderName = "TakeOffField")]
        public string ReturnedFrom => ((eFlightsFields)this.ReturingField).GetDescription();

        public int ReturingField { get; set; }

        [ExportToExcel(ResourceType = typeof(TripsStrings), HeaderName = "ID")]
        public int TripID { get; set; }

        [ExportToExcel(ResourceType = typeof(ExpeditionStrings), HeaderName = "BusesRequiredPerDay")]
        public int BusesRequiredPerDay { get; set; }

        [ExportToExcel(ResourceType = typeof(ExpeditionStrings), HeaderName = "RegisteredPassengers")]
        public int RegisteredPassengers { get; set; }

        [ExportToExcel(ResourceType = typeof(GroupFormsStrings), HeaderName = "CostPerStudent")]
        public double CostPerStudent { get; set; }

        [ExportToExcel(ResourceType = typeof(ExpeditionStrings), HeaderName = "Status")]
        public string Status => ((eExpeditionStatus)this.ExpeditionStatus).GetDescription();

        public int ExpeditionStatus { get; set; }
        public eExpeditionStatus ExpeditionStatusEnum => (eExpeditionStatus)this.ExpeditionStatus;

        [ExportToExcel(ResourceType = typeof(ExpeditionStrings), HeaderName = "ID")]
        public int ExpeditionID { get; set; }

        [ExportToExcel(ResourceType = typeof(ExpeditionStrings), HeaderName = "Agency")]
        public string AgencyName { get; set; }

        [ExportToExcel(ResourceType = typeof(GroupsStrings), HeaderName = "ExpeditionID")]
        public string GroupExternalID { get; set; }

    }
}

FlightScheduling.Web/Areas/Administration/Models/Reports/BusesPerDayViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Endilo.ExportToExcel;
using FlightScheduling.Language;

namespace FlightScheduling.Web.Areas.Administration.Models.Reports
{
    public class BusesPerDayViewModel
    {
       

        [ExportToExcel(ResourceType = typeof(ReportsStrings), HeaderName = "Day")]
        public DateTime Day { get; set; }

        [ExportToExcel(ResourceType = typeof(ReportsStrings), HeaderName = "BusesPerDayCount")]
        public int BusesPerDay { get; set; }

        [ExportToExcel(ResourceType = typeof(ReportsStrings), HeaderName = "ExpeditionPerDayCount")]
        public int ExpeditionPerDay { get; set; }


    }

    public class BusesPerDayReportViewModel
    {
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(CommonStrings), Name = "FromDate")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(CommonStrings), Name = "To")]
        public DateTime EndDate { get; set; }

        public List<BusesPerDayViewModel> BusesPerDayList { get; set; }

        public BusesPerDayReportViewModel()
        {
            StartDate = new DateTime(DateTime.Now.Year,1,1);
            EndDate = new DateTime(DateTime.Now.Year,12,31);
            BusesPerDayList = new List<BusesPerDayViewModel>();
        }
    }

    

    
}

FlightScheduling.Web/Areas/Administration/Models/Reports/SchoolGlobalRemarksViewModel.cs
using Endilo.ExportToExcel;
using FlightScheduling.Language;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FlightScheduling.Web.Areas.Administration.Models.Reports
{
    public class SchoolGlobalRemarksViewModel
    {
        public int ID { get; set; }

        public int SchoolID { get; set; }

        [ExportToExcel(ResourceType = typeof(ReportsStrings), HeaderName = "CsvComment")]
        [Display(ResourceType = typeof(ReportsStrings), Name = "CsvComment")]
        public string Notes { get; set; }

        [ExportToExcel(ResourceType = typeof(ReportsStrings), HeaderName = "CsvComment")]
        [Display(ResourceType = typeof(ReportsStrings), Name = "CsvComment")]
        public DateTime UpdateDate { get; set; }

        [ExportToExcel(ResourceType = typeof(SchoolsStrings), HeaderName = "InstituteID")]
        [Display(ResourceType = typeof(SchoolsStrings), Name = "InstituteID")]
        public int InstituteID { get; set; }

        [ExportToExcel(ResourceType = typeof(SchoolsStrings), HeaderName = "Name")]
        [Display(ResourceType = typeof(SchoolsStrings), Name = "Name")]
        public string SchoolName { get; set; }

        public string Firstname { get; set; }

        public string Lastname { get; set; }

        [ExportToExcel(ResourceType = typeof(CommonStrings), HeaderName = "FullName")]
        [Display(ResourceType = typeof(CommonStrings), Name = "FullName")]
        public string FullName => $"{Firstname} {Lastname}";

    }

    public class SchoolGlobalRemarkReportViewModel
    {
        public IEnumerable<SchoolGlobalRemarksViewModel> Items { get; set; }

        public SchoolGlobalRemarkReportViewModel()
        {
            Items = new List<SchoolGlobalRemarksViewModel>();
        }

    }
}

FlightScheduling.Web/Areas/Administration/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Endilo.ExportToExcel;
using FlightScheduling.DAL;
using FlightScheduling.Language;
using FlightScheduling.Web.Areas.Administration.Models.Flights;
using FlightScheduling.Web.Areas.Administration.Models.Reports;
using System.Data.Entity;
using Endilo.Helpers;
using Flight.DAL.FlightDB.Methods;
using FlightScheduling.Website.Infrastructure;
using System.Text;
using System.IO;
using AutoMapper;
using FlightScheduling.DAL.CustomEntities;
using CsvHelper;
using FlightScheduling.Web.Areas.Administration.Models.Common;
using FlightScheduling.Web.Infrastructure;
using FlightScheduling.DAL.CustomEntities.Permissions;
using Otakim.Website.Infrastructure;

namespace FlightScheduling.Web.Areas.Administration.Controllers
{
    public class ReportsController : Controller
    {

        private FlightDB _db = new FlightDB();
        DBRepository _dbDapper = new DBRepository();

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult GetReports()
        {



            return View();
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_BusesPerDay)]
        public ActionResult GetBusesPerDay()
        {
            BusesPerDayReportViewModel model = new BusesPerDayReportViewModel();
            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_BusesPerDay)]
        [HttpPost]
        public ActionResult GetBusesPerDay(BusesPerDayReportViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.BusesPerDayList = _db.BusesPerDay(model.StartDate, model.EndDate).Select(r => new BusesPerDayViewModel()
                {
                    Day = (DateTime)r.Date,
                    BusesPerDay = (int)r.BusesPerDay,
                    ExpeditionPerDay = (int)r.ExpeditionsPerDay
                }).ToList();

                Session.Add("BusesPerDayReport", model.BusesPerDayList);

                return View(model);
            }



            return View(model);
        }


        [PermissionAuthorization(PermissionBitEnum.Reports_AvailableSeats)]
        public ActionResult GetFlightSeatsAvailability()
        {

            FlightSeatsAvailabilityReportViewModel model = new FlightSeatsAvailabilityReportViewModel();

            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_AvailableSeats)]
        [HttpPost]
        public ActionResult GetFlightSeatsAvailability(FlightSeatsAvailabilityReportViewModel model)
        {

            if (ModelState.IsValid)
            {
                model.Data = _dbDapper.GetRecords<RemainingSeatsInFLightsViewModel>(QueriesRepository.GetTripAvilabilitySeats, new { model.StartDate, model.EndDate }).ToList();

                Session.Add("AvailableSeats", model);
            }


            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_Agencies)]
        [HttpGet]
        public ActionResult AgencyReport()
        {
            AgencyReportContainerViewModel model = new AgencyReportContainerViewModel();

            Users _user = _db.GetUserByLoginName(User.Identity.Name);
            List<AgencyReportViewModel> reportdata = new List<AgencyReportViewModel>();
            if (_user.RuleEnum.Equals(eRole.Agent))
            {
                model.Data =
                    _dbDapper.GetAgencyReport<AgencyReportViewModel>(QueriesRepository.GetAgencyReport, model.StartDate, model.EndDate, _user.AgencyID, (int)eExpeditionStatus.Rejected).ToList();
            }
            else if (_user.RuleEnum.Equals(eRole.Viewer))
            {
                model.Data = _dbDapper.GetAgencyReport<AgencyReportViewModel>(QueriesRepository.GetAgencyReport, model.StartDate, model.EndDate, null, (int)eExpeditionStatus.Rejected).ToList();
            }
            else
            {
                model.Data = _dbDapper.GetAgencyReport<AgencyReportViewModel>(QueriesRepository.GetAgencyReport, model.StartDate, model.EndDate, null, (int)eExpeditionStatus.Rejected).ToList();
            }

            Session.Add("AgencyReportData", model.Data);

            return View("AgencyReport", model);


        }

        [PermissionAuthorization(PermissionBitEnum.Reports_Agencies)]
        [HttpPost]
        public ActionResult AgencyReport(AgencyReportContainerViewModel model)
        {
            Users _user = _db.GetUserByLoginName(User.Identity.Name);
            List<AgencyReportViewModel> reportdata = new List<AgencyReportViewModel>();
            if (_user.RuleEnum.Equals(eRole.Agent))
            {
                model.Data =
                    _dbDapper.GetAgencyReport<AgencyReportViewModel>(QueriesRepository.GetAgencyReport, model.StartDate, model.EndDate, _user.AgencyID, (int)eExpeditionStatus.Rejected).ToList();
            }
            else if (_user.RuleEnum.Equals(eRole.Viewer))
            {
                model.Data = _dbDapper.GetAgencyReport<AgencyReportViewModel>(QueriesRepository.GetAgencyReport, model.StartDate, model.EndDate, null, (int)eExpeditionStatus.Rejected).ToList();
            }
            else
            {
                model.Data = _dbDapper.GetAgencyReport<AgencyReportViewModel>(QueriesRepository.GetAgencyReport, model.StartDate, model.EndDate, null, (int)eExpeditionStatus.Rejected).ToList();
            }

            Session.Add("AgencyReportData", model.Data);

            return View("AgencyReport", model);
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_Agencies)]
        [HttpGet]
        public ActionResult AgencyReportExport()
        {
            if (Session["AgencyReportData"] != null)
            {
                ExportToExcel<AgencyReportViewModel> exc = new ExportToExcel<AgencyReportViewModel>((List<AgencyReportViewModel>)Session["AgencyReportData"], ReportsStrings.AgencyReport);
                var stream = exc.GetFile();
                string fileName = String.Format("{0} {1}.xlsx", ReportsStrings.AgencyReport, DateTime.Now.ToString("dd-MM-yyyy hh:ss"));
                string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

                stream.Position = 0;
                return File(stream, contentType, fileName);
            }

            return null;
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_Flights)]
        public ActionResult FlightsReport()
        {
            FlightsReportMainViewModel model = new FlightsReportMainViewModel();

            model.FlightsReportViewModels = GetFlights(model.FilterFromDate, model.FilterToDate);

            Session.Add("FlightsReport", model.FlightsReportViewModels);

            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_Flights)]
        private List<FlightsReportViewModel> GetFlights(DateTime FromDate, DateTime ToDate)
        {
            Users _user = _db.GetUserByLoginName(User.Identity.Name);



            var reportData = (from exflights in _db.ExpeditionsFlights
                              join flights in _db.Flights on exflights.FlightID equals flights.ID
                              join Expeditions in _db.Expeditions on exflights.ExpeditionID equals Expeditions.ID
                              join Trips in _db.Trips on Expeditions.TripID equals Trips.ID
                              where Expeditions.Status == 2 && Trips.DepartureDate >= FromDate && Trips.DepartureDate <= ToDate
                              select new
                              {
                                  TripID = Trips.ID,
                                  DepartureDate = Trips.DepartureDate,
                                  ReturnDate = Trips.ReturningDate,
                                  FlightID = exflights.FlightID,
                                  AirlineName = flights.AirlineName,
                                  NumberOfPassengers = exflights.NumberOfPassengers,
                                  TakeOffFromIsrael = flights.TakeOffFromIsrael,
                                  FlightDepartureFieldID = (FlightViewModel.FlightsFields)flights.DepartureFieldID,
                                  FlightDestinationID = (FlightViewModel.FlightsFields)flights.DestinationID,
                                  FlightDepartureDate = flights.StartDate,
                                  ExpeditionID = exflights.ExpeditionID,
                                  RegisteredPassengers = exflights.NumberOfPassengers,
                                  AgencyID = Expeditions.AgencyID
                              }).ToList();

            if (_user.RuleEnum.Equals(eRole.Agent))
            {
                reportData = reportData.Where(e => e.AgencyID.Equals(_user.AgencyID)).ToList();
            }


            List<FlightsReportViewModel> flightsList = reportData.Select(r => new FlightsReportViewModel()
            {
                TripID = r.TripID,
                DepartureDate = r.DepartureDate,
                ReturnDate = r.ReturnDate,
                FlightID = r.FlightID,
                AirlineName = r.AirlineName,
                FlightDestenation = r.FlightDepartureFieldID.GetDescription(),
                FlightReturnField = r.FlightDestinationID.GetDescription(),
                FlightDate = r.FlightDepartureDate,
                TakeOffIsrael = r.TakeOffFromIsrael.Value ? ReportsStrings.Yes : ReportsStrings.No,
                NumberOfPassengers = r.NumberOfPassengers,
                ExpeditionID = r.ExpeditionID,
                RegisteredPassengers = r.RegisteredPassengers
            }).ToList();

            return flightsList;
        }

        [PermissionAuthorization(PermissionBitEnum.Reports_Flights)]
        [HttpPost]

FlightScheduling.Web/Areas/Administration/Views/Reports/AgencyReport.cshtml
@using FlightScheduling.Language
@using MvcContrib.UI.Grid
@model FlightScheduling.Web.Areas.Administration.Models.Reports.AgencyReportContainerViewModel

@{
    /**/

    ViewBag.Title = "AgencyReport";
    Layout = "~/Views/Shared/_Reports.cshtml";
}

@section styles
{
    @Styles.Render("~/Content/css/datepicker")
}

<h2>@ReportsStrings.AgencyReport</h2>

@using (Html.BeginForm("AgencyReport", "Reports", FormMethod.Post))
{
    <div class="form-group col-md-4 col-sm-6 col-xs-12">
        @Html.LabelFor(model => model.StartDate, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.StartDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", @value = @DateTime.Now })
        @Html.ValidationMessageFor(m => m.StartDate)
    </div>

    <div class="form-group col-md-4 col-sm-6 col-xs-12">
        @Html.LabelFor(model => model.EndDate, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.EndDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", @value = @DateTime.Now })
        @Html.ValidationMessageFor(m => m.EndDate)
    </div>

    <div class="col-md-4 col-sm-6 col-xs-12 search-button-padding">
        <input type="submit" value="@CommonStrings.Send" class="btn btn-default pull-left" />
    </div>

    <div class="clearfix">&nbsp;</div>
    <div class="clearfix">&nbsp;</div>
    <div class="clearfix">&nbsp;</div>
}

<a href="@Url.Action("AgencyReportExport")" title="@CommonStrings.ExportToExcel">@Html.Raw(Html.GetIcon(Icons.Excel, CommonStrings.ExportToExcel).ToHtmlString())  @CommonStrings.ExportToExcel</a>


@Html.Grid(Model.Data).Columns(col =>
{
    col.For(c => c.GroupExternalID).Named(GroupsStrings.ExpeditionID);
    col.For(c => c.SchoolID).Named(SchoolsStrings.ID);
    col.For(c => c.InstituteID).Named(SchoolsStrings.InstituteID);
    col.For(c => c.SchoolName).Named(SchoolsStrings.Name);
    col.For(c => c.Region).Named(SchoolsStrings.Region);
    col.For(c => c.TripID).Named(TripsStrings.ID);
    col.For(c => c.DepartureDate.ToString("dd/MM/yyyy")).Named(TripsStrings.DepartureDate);
    col.For(c => c.ReturnDate.ToString("dd/MM/yyyy")).Named(TripsStrings.ReturnDate);
    col.For(c => c.Destenation).Named(TripsStrings.Destenation);
    col.For(c => c.ReturnedFrom).Named(FlightsStrings.DepartureField);
    col.For(c => c.BusesRequiredPerDay).Named(ExpeditionStrings.NumOfBuses);
    col.For(c => c.RegisteredPassengers).Named(ExpeditionStrings.RegisteredPassengers);
    col.For(c => c.CostPerStudent == 0 ? "" : c.CostPerStudent.ToString()).Named(GroupFormsStrings.CostPerStudent);
    col.For(c => @Html.GetStatusTag(c.ExpeditionStatusEnum).ToHtmlString()).Named(ExpeditionStrings.Status).Encode(false);
    col.For(c => c.ExpeditionID).Named(ExpeditionStrings.ID);
    col.For(c => c.AgencyName).Named(ExpeditionStrings.Agency);
}).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "tripsManagement").Empty(CommonStrings.Empty)

@section scripts
{

    @Scripts.Render("~/bundles/datepicker")

}

FlightScheduling.Web/Areas/Administration/Views/Reports/EmergencyContactReport.cshtml
@using FlightScheduling.Language
@using FlightScheduling.Web.Infrastructure
@model FlightScheduling.Web.Areas.Administration.Models.Reports.EmerhencyContactReportViewModel
@using MvcContrib.UI.Grid

@{
    ViewBag.Title = "FlightsReport";
    Layout = "~/Views/Shared/_Reports.cshtml";
}

@section styles
{
    @Styles.Render("~/Content/css/datepicker")
}

<h2>@ReportsStrings.EmerhencyContactReport</h2>
@*<h4>@Html.ActionLink("ייצא לאקסל", "ExportEmergencyContactReport")</h4>*@

@using (Html.BeginForm("GetEmergencyContactReport", "Reports", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.TargetDate, new { @class = "control-label col-md-1" })
        <div class="col-md-2">
            @Html.TextBoxFor(model => model.TargetDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
        </div>
    </div>
    <div class="col-md-2">
        <input type="submit" value="@CommonStrings.Search" class="btn btn-default" />
    </div>


        <div class="clearfix">&nbsp;</div>
        <div class="clearfix">&nbsp;</div>
        <div class="clearfix">&nbsp;</div>
}

<a href="@Url.Action("ExportEmergencyContactReport")" title="@CommonStrings.ExportToExcel">@Html.Raw(Html.GetIcon(Icons.Excel, CommonStrings.ExportToExcel).ToHtmlString())  @CommonStrings.ExportToExcel</a>

@Html.Grid(Model.Items).Columns(col =>
{
    col.For(c => c.GroupID).Named(ReportsStrings.CsvGroupID);
    col.For(c => c.SchoolName).Named(ReportsStrings.CsvSchoolName);
    col.For(c => c.RegionEnum != null ? c.RegionEnum.GetDescription() : "").Named(ReportsStrings.csvSchoolRegion);
    col.For(c => c.EmergencyContactName).Named(ReportsStrings.csvGroupEmergancyContactName);
    col.For(c => c.EmergencyContactPhone).Named(ReportsStrings.csvGroupEmergancyContactPhone);
    col.For(c => c.SchoolManagerName).Named(ReportsStrings.CsvSchoolMangerName);
    col.For(c => c.SchoolManagerPhone).Named(ReportsStrings.CsvSchoolMangerPhone);
}).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "EmergencyContactReport").Empty(CommonStrings.Empty)

@section scripts
{

    @Scripts.Render("~/bundles/datepicker");

}

FlightScheduling.Web/Areas/Administration/Views/Reports/ExpeditionStatusReport.cshtml
@using FlightScheduling.Language
@using Flight.DAL.FlightDB.Methods
@using FlightScheduling.Web.Infrastructure
@model FlightScheduling.Web.Areas.Administration.Models.Reports.ExpeditionReportViewModel
@using MvcContrib.UI.Grid

@{
    ViewBag.Title = "FlightsReport";
    Layout = "~/Views/Shared/_Reports.cshtml";
}

@section styles
{
    @Styles.Render("~/Content/css/datepicker")
}

<h2>@ReportsStrings.ExpeditionStatusReport</h2>
@*<h4>@Html.ActionLink("ייצא לאקסל", "ExportFlightReport")</h4>*@

@using (Html.BeginForm("GetExpeditionStatusReport", "Reports", FormMethod.Post))
{
    <div class="row">
        <div class="form-group col-md-4 col-sm-6 col-xs-12">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.StartDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
        </div>

        <div class="form-group col-md-4 col-sm-6 col-xs-12">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.EndDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
        </div>

        <div class="form-group col-md-4 col-sm-6 col-xs-12">
            @Html.LabelFor(model => model.Status, new { @class = "control-label" })
            @Html.EnumDropDownListFor(model => model.Status, CommonStrings.SelectValue, new { @class = "form-control" })
        </div>

    </div>
    <div class="row">
        <div class="col-xs-12">
            <input type="submit" value="@CommonStrings.Search" class="btn btn-default pull-left" />
        </div>
    </div>

    <div class="clearfix">&nbsp;</div>
    <div class="clearfix">&nbsp;</div>
    <div class="clearfix">&nbsp;</div>
}

<a href="@Url.Action("ExportExpeditionStatusReport")" title="@CommonStrings.ExportToExcel">@Html.Raw(Html.GetIcon(Icons.Excel, CommonStrings.ExportToExcel).ToHtmlString())  @CommonStrings.ExportToExcel</a>

@Html.Grid(Model.Items).Columns(col =>
{
    col.For(c => c.ExpeditionId).Named(ReportsStrings.CsvOrderID);
    col.For(c => c.Status).Named(ReportsStrings.csvExpeditionStatus);
    col.For(c => c.SchoolName).Named(ReportsStrings.CsvSchoolName);
    col.For(c => c.InstituteID).Named(ReportsStrings.CsvInstituteID);
    col.For(c => c.Region).Named(ReportsStrings.csvSchoolRegion);
    col.For(c => c.NumOfPassenges).Named(ReportsStrings.CsvNumberOfPassengers);
    col.For(c => c.NumOfBuses).Named(ReportsStrings.CsvNumberOfBuses);
    col.For(c => c.DepartureDate).Named(ReportsStrings.CsvDepartureDate).Format(AppConfig.FormatDateGrid);
    col.For(c => c.Manager).Named(ReportsStrings.CsvSchoolMangerName);
    col.For(c => c.ManagerPhone).Named(ReportsStrings.CsvSchoolMangerPhone);
    col.For(c => c.ManagerCell).Named(ReportsStrings.CsvSchoolMangerCell);
    col.For(c => c.ManagerEmail).Named(ReportsStrings.CsvSchoolMangerEmail);
}).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "groupsReport").Empty(CommonStrings.Empty)

@section scripts
{

    @Scripts.Render("~/bundles/datepicker")

}