FlightScheduling.Web/Areas/Administration/Models/Trips/ExpeditionsViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using FlightScheduling.Language;
using FlightScheduling.DAL;
using FlightScheduling.Web.Areas.Administration.Models.Flights;
using FlightScheduling.Web.Models.Expeditions;
using FlightScheduling.Web.Areas.Administration.Models.Common;

namespace FlightScheduling.Web.Areas.Administration.Models.Trips
{
    public class ExpeditionFlightViewModel
    {
        
        [Display(ResourceType = typeof(ExpeditionStrings), Name = "ID")]
        public int ExpeditionID { get; set; }

        public ExpeditionsViewModel Expedition { get; set; }
        
        public List<FlightDetailsViewModel> DepartureFLights { get; set; }
        public List<FlightDetailsViewModel> ReturningFLights { get; set; }



        public ExpeditionFlightViewModel()
        {
            DepartureFLights = new List<FlightDetailsViewModel>();
            ReturningFLights = new List<FlightDetailsViewModel>();
            

            Expedition = new ExpeditionsViewModel();
        }

    }


    public class FlightDetailsViewModel
    {
        [Display(ResourceType = typeof(FlightsStrings), Name = "ID")]
        public int ID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(ResourceType = typeof(FlightsStrings), Name = "DepartureDate")]
        public DateTime? DepartureDate { get; set; }

        [Display(ResourceType = typeof(FlightsStrings), Name = "DepartureField")]
        public FlightViewModel.FlightsFields DepartureField { get; set; }

        public bool TakeOffFromIsrael { get; set; }

        [Display(ResourceType = typeof(FlightsStrings), Name = "DestenationField")]
        public FlightViewModel.FlightsFields DestenationField { get; set; }

        [Display(ResourceType = typeof(FlightsStrings), Name = "NumberOfPassengers")]
        public int NumberOfPassengers { get; set; }

        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(FlightsStrings), Name = "AirlineName")]
        public string AirlineName { get; set; }

        [Display(ResourceType = typeof(FlightsStrings), Name = "FlightNumber")]
        public string FlightNumber { get; set; }

        [Display(ResourceType = typeof(FlightsStrings), Name = "Comments")]
        public string Comments { get; set; }

        //Properties
        public int RemainingSeats { get; set; }

        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(FlightsStrings), Name = "AssignPassengers")]
        public int AssignPassengers { get; set; }

        public FlightDetailsViewModel()
        {
            RemainingSeats = 0;
        }
    }


    public class MoveOrderViewModel
    {
        public int OrderID { get; set; }
        [Required(ErrorMessageResourceType = typeof(ValidationStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(TripsStrings), Name = "SelectTrip")]
        public CustomSelectList Trips { get; set; }

        public int TripID { get; set; }

        public MoveOrderViewModel()
        {
            Trips = new CustomSelectList();
        }
    }

    public class FutureTripsViewModel
    {
        public int ID { get; set; }
        public DateTime DepartureDate { get; set; }
        public int DestinationID { get; set; }
    }

}

FlightScheduling.Web/Models/Expeditions/FullCalendar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FlightScheduling.Web.Models.Expeditions
{
    public class FullCalendar
    {
        public List<FullCalendarEvent> events { get; set; }

        public FullCalendar()
        {
            events = new List<FullCalendarEvent>();
        }
    }

    public class FullCalendarEvent
    {
        public string id { get; set; }
        public string title { get; set; }
        public bool allDay { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public string rendering { get; set; }
        public string backgroundColor { get; set; }
        public string eventBackgroundColor { get; set; }
        public string color { get; set; }
        public string overlap { get; set; }
        public string url { get; set; }

    }

    public enum EventRendering
    {
        background,
        inversebackground
    }


}

FlightScheduling.Web/Models/Expeditions/GanttData.cs
using System;
using System.Collections.Generic;

namespace FlightScheduling.Web.Models.Expeditions
{
    public class GanttData
    {
        public int id { get; set; }
        public string title { get; set; }
        public string tooltip { get; set; } = string.Empty;
        public string start { get; set; }
        public string end { get; set; }
        public bool editable { get; set; }
        public int numberOfBuses { get; set; }

        public string color { get; set; } = "#E3178E";

        public IEnumerable<int> resource { get; set; }
        public GanttData()
        {
            
        }

        public GanttData(
            int id, 
            string title, 
            string tooltip, 
            DateTime start, 
            DateTime end,
            List<int> resource,
            int numberOfBuses,
            string color = "#E3178E")
        {
            this.id = id;
            this.title = title;
            this.tooltip = tooltip;
            this.start = start.ToString("yyyy-MM-ddTHH:mm:ss");
            this.end = end.ToString("yyyy-MM-ddTHH:mm:ss");
            this.editable = false;
            this.resource = resource;
            this.numberOfBuses = numberOfBuses;
            this.color = color;
        }
    }
}

FlightScheduling.Web/Models/Expeditions/GanttViewModel.cs
using System.Collections.Generic;

namespace FlightScheduling.Web.Models.Expeditions
{
    public class GanttViewModel
    {
        public IEnumerable<GanttData> Date { get; set; }
    }
}

FlightScheduling.Web/Areas/Administration/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Endilo.GenericSearch;
using Flight.DAL.FlightDB.Methods;
using FlightScheduling.DAL;
using FlightScheduling.Web.Areas.Administration.Models.Common;
using FlightScheduling.Web.Areas.Administration.Models.Flights;
using FlightScheduling.Web.Areas.Administration.Models.Trips;
using Otakim.Website.Infrastructure;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using FlightScheduling.Web.Models.Expeditions;
using FlightScheduling.Web.Infrastructure;
using Endilo.Helpers;
using System.IO;
using LinqToExcel;
using AutoMapper;
using FlightScheduling.DAL.CustomEntities.Permissions;

namespace FlightScheduling.Web.Areas.Administration.Controllers
{
    [PermissionAuthorization(PermissionBitEnum.Trip_View)]
    public class TripsController : Controller
    {
        private FlightDB _db = new FlightDB();
        DBRepository _dbDapper = new DBRepository();

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult GetTrips()
        {
            TripsViewModel model = new TripsViewModel();

            if (Session["TripFilterFromDate"] != null)
            {
                model.FilterFromDate = (DateTime)Session["TripFilterFromDate"];
            }
            else
            {
                model.FilterFromDate = SystemConfigurationRepository.TripsFilterStartDate;
            }

            if (Session["TripFilterToDate"] != null)
            {
                model.FilterToDate = (DateTime)Session["TripFilterToDate"];
            }
            else
            {
                model.FilterToDate = SystemConfigurationRepository.TripsFilterEndDate;
            }




            model.TripViewModelBasics = _db.Trips.Include(t => t.Expeditions).RemoveInActive().Where(t => t.DepartureDate >= DateTime.Now && t.DepartureDate <= DateTime.Now.AddYears(1)).Select(t => new TripViewModelBasic()
            {
                ID = t.ID,
                DepartureDate = t.DepartureDate,
                UpdatenDate = t.UpdateDate,
                ReturnDate = t.ReturningDate,
                Destenation = (FlightViewModel.FlightsFields)t.DestinationID,
                ReturnedFrom = (FlightViewModel.FlightsFields)t.ReturingField,
                Comments = t.Comments,
                CreationDate = t.CreationDate,
                NumberOfExpeditions = t.Expeditions.Count(e => e.Status.Equals((int)eExpeditionStatus.PendingApproval))
            }).ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult GetTrips(DateTime? FilterFromDate, DateTime? FilterToDate)
        {
            TripsViewModel model = new TripsViewModel();


            if (FilterFromDate == null && Session["TripFilterFromDate"] == null)
            {
                FilterFromDate = SystemConfigurationRepository.TripsFilterStartDate;
            }
            else if (Session["TripFilterFromDate"] != null && FilterFromDate == null)
            {
                FilterFromDate = (DateTime)Session["TripFilterFromDate"];
            }

            if (FilterToDate == null && Session["TripFilterToDate"] == null)
            {
                FilterToDate = SystemConfigurationRepository.TripsFilterEndDate;
            }
            else if (Session["TripFilterToDate"] != null && FilterToDate == null)
            {
                FilterToDate = (DateTime)Session["TripFilterToDate"];
            }

            //Set Filters session
            Session["TripFilterFromDate"] = FilterFromDate;
            Session["TripFilterToDate"] = FilterToDate;

            model.TripViewModelBasics = _db.Trips.Include(t => t.Expeditions).RemoveInActive().Where(t => t.DepartureDate >= FilterFromDate && t.DepartureDate <= FilterToDate).Select(t => new TripViewModelBasic()
            {
                ID = t.ID,
                DepartureDate = t.DepartureDate,
                UpdatenDate = t.UpdateDate,
                ReturnDate = t.ReturningDate,
                Destenation = (FlightViewModel.FlightsFields)t.DestinationID,
                ReturnedFrom = (FlightViewModel.FlightsFields)t.ReturingField,
                Comments = t.Comments,
                CreationDate = t.CreationDate,
                NumberOfExpeditions = t.Expeditions.Count(e => e.Status.Equals((int)eExpeditionStatus.PendingApproval) && e.Status.Equals((int)eExpeditionStatus.InProcess))
            }).ToList();

            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Trip_Edit)]
        [HttpGet]
        public ActionResult AddTrip()
        {
            TripViewModelBasic model = new TripViewModelBasic();

            if (Request.IsAjaxRequest())
            {
                return PartialView("_AddTrip", model);
            }
            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Trip_Edit)]
        [HttpPost]
        public ActionResult AddTrip(TripViewModelBasic model)
        {
            if (ModelState.IsValid)
            {
                Trips _trip = new Trips();
                _trip.CreationDate = DateTime.Now;
                _trip.UpdateDate = DateTime.Now;
                _trip.DepartureDate = (DateTime)model.DepartureDate;
                _trip.DestinationID = (int)model.Destenation;
                _trip.ReturingField = (int)model.ReturnedFrom;
                _trip.ReturningDate = model.ReturnDate;
                _trip.Comments = model.Comments;
                _trip.IsActive = true;

                _db.Trips.Add(_trip);

                int results = _db.SaveChanges();

                return RedirectToAction("GetTrips");
            }

            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Trip_Edit)]
        [HttpGet]
        public ActionResult EditTrip(int ID)
        {
            Trips trip = _db.Trips.FirstOrDefault(t => t.ID.Equals(ID));
            TripViewModelBasic model = new TripViewModelBasic();
            model.ID = trip.ID;
            model.IsActive = trip.IsActive;
            model.Comments = trip.Comments;
            model.DepartureDate = trip.DepartureDate;
            model.Destenation = (FlightViewModel.FlightsFields)trip.DestinationID;
            model.ReturnDate = trip.ReturningDate;
            model.ReturnedFrom = (FlightViewModel.FlightsFields)trip.ReturingField;
            model.UpdatenDate = trip.UpdateDate;


            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Trip_Edit)]
        [HttpPost]
        public ActionResult EditTrip(TripViewModelBasic model)
        {
            if (ModelState.IsValid)
            {

                Trips trip = _db.Trips.FirstOrDefault(t => t.ID.Equals(model.ID));

                trip.Comments = model.Comments;
                trip.DepartureDate = (DateTime)model.DepartureDate;
                trip.DestinationID = (int)model.Destenation;
                trip.ReturingField = (int)model.ReturnedFrom;
                trip.ReturningDate = model.ReturnDate;
                trip.UpdateDate = DateTime.Now;

                int results = _db.SaveChanges();

                return RedirectToAction("GetTrips");
            }

            return View(model);
        }

        [PermissionAuthorization(PermissionBitEnum.Trip_Edit)]
        [HttpGet]
        public ActionResult TripManagement(int ID)
        {
            TripManagementViewModel model = new TripManagementViewModel();

            Trips trip =
                _db.Trips.Include(t => t.Expeditions).Include(t => t.Flights).Include(t => t.Flights).Include(t => t.Flights.Select(f => f.ExpeditionsFlights)).FirstOrDefault(t => t.ID.Equals(ID));

            //Load Basic trip information
            model.TripViewModelBasic = new TripViewModelBasic()
            {
                ID = trip.ID,
                DepartureDate = trip.DepartureDate,
                UpdatenDate = trip.UpdateDate,
                ReturnDate = trip.ReturningDate,
                Destenation = (FlightViewModel.FlightsFields)trip.DestinationID,
                ReturnedFrom = (FlightViewModel.FlightsFields)trip.ReturingField,
                Comments = trip.Comments,
                CreationDate = trip.CreationDate
            };




            // Loading Summary information
            model.TripSummaryDetailsViewModel.NumOfBuses =
                trip.Expeditions.Where(e => e.TripID.Equals(ID) && e.IsActive && (e.Status.Equals((int)eExpeditionStatus.Approved) || e.Status.Equals((int)eExpeditionStatus.InProcess))).Sum(e => e.BasesPerDay);

            model.TripSummaryDetailsViewModel.NumberOfOutGoingFlights =
                trip.Flights.Count(f => f.IsActive && f.TakeOffFromIsrael == true);

            model.TripSummaryDetailsViewModel.NumberOfInComingFlights =
                trip.Flights.Count(f => f.IsActive && f.DestinationID.Equals((int)FlightViewModel.FlightsFields.Israel));

            model.TripSummaryDetailsViewModel.NumOfExpeditions =
                trip.Expeditions.Count(e => e.IsActive && e.TripID.Equals(ID) && (e.Status.Equals((int)eExpeditionStatus.Approved) || e.Status.Equals((int)eExpeditionStatus.InProcess)));

            //Load expedition Flights


            // Load out going flights
            model.TripOutGoingFlightsViewModel.FlightViewModels =
                trip.Flights.Where(f => f.IsActive && f.TakeOffFromIsrael == true).Select(f => new FlightManagementViewModel()
                {
                    ID = f.ID,
                    AirlineName = f.AirlineName,
                    CreationDate = f.CreationDate,
                    UpdatenDate = f.UpdateDate,
                    TakeOffFromIsrael = (bool)f.TakeOffFromIsrael,
                    DepartureDate = f.StartDate,

FlightScheduling.Web/Areas/Administration/Views/Trips/TripManagement.cshtml
@model FlightScheduling.Web.Areas.Administration.Models.Trips.TripManagementViewModel

@{
    ViewBag.Title = "TripManagement";
    Layout = "~/Views/Shared/_AdministrationLayout.cshtml";
}
@section styles
{
    @Styles.Render("~/Content/css/datepicker")
    @Styles.Render("~/bundles/css/chosen")
}
<div class="innerTripDetails">
    <div class="row section">

        <div class="col-lg-6 col-md-6 col-sm-12">
            <!-- Trip Details -->
            @Html.Partial("_TripDetails", Model.TripViewModelBasic)
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <!-- Trip Summary -->
            @Html.Partial("_TripSummary", Model.TripSummaryDetailsViewModel)
        </div>
    </div>
    <div class="row section">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <!-- Departure Flights -->
            @Html.Partial("_DepartureFlights", Model.TripOutGoingFlightsViewModel)
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <!-- Returning Flighs -->
            @Html.Partial("_ReturningFlights", Model.TripInComingFlightsViewModel)
        </div>
    </div>
    <div class="row section">
        <div class="col-lg-12">
            @Html.Partial("_Expeditions", Model.Expeditions)
        </div>
    </div>
</div>

<div id="TripModalWindowContainer" class="modal fade"></div>
<div id="TripLoadingPanelContainer" class="modal-loading-panel" style="display:none"></div>

@section scripts
{

    @Scripts.Render("~/bundles/datepicker")
    @Scripts.Render("~/bundles/chosen")

}

FlightScheduling.Web/Areas/Administration/Views/Trips/_AddTrip.cshtml
@using FlightScheduling.Language
@model FlightScheduling.Web.Areas.Administration.Models.Trips.TripViewModelBasic


@using (Html.BeginForm("AddTrip", "Trips", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-validation", id = "form-add-trip" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>@TripsStrings.AddTripTitle</h4>
            </div>
            <div class="modal-body">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="form-horizontal">


                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            @Html.LabelFor(model => model.DepartureDate, new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.DepartureDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker", @value = @DateTime.Now })
                            @Html.ValidationMessageFor(model => model.DepartureDate)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Destenation, new { @class = "control-label " })
                            @Html.EnumDropDownListFor(model => model.Destenation, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Destenation)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ReturnDate, new { @class = "control-label " })
                            @Html.TextBoxFor(model => model.ReturnDate, "{0:dd/MM/yyyy}", new { @class = "form-control datepicker" })
                            @Html.ValidationMessageFor(model => model.ReturnDate)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ReturnedFrom, new { @class = "control-label " })
                            @Html.EnumDropDownListFor(model => model.ReturnedFrom, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ReturnedFrom)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Comments, new { @class = "control-label " })
                            @Html.TextBoxFor(model => model.Comments, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Comments)
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default validate-form">
                    <span class="button-text">@CommonStrings.SaveAndClose</span>
                    <div class="white-v"></div>
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">@CommonStrings.Close</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript" src="~/Scripts/Common/jquery.validate.filetypevalidation.js"></script>
<script type="text/javascript" src="~/Scripts/Common/validate.form.custom.methods.js"></script>
<script type="text/javascript" src="~/Scripts/pickadate/datepicker.ajaxload.init.js"></script>
@*~/Scripts/pickadate/datepicker.ajaxload.init.js*@

@section scripts
{

    @Scripts.Render("~/bundles/datepicker");

}

FlightScheduling.Web/Areas/Administration/Views/Trips/_LinkReturningFlights.cshtml
@using FlightScheduling.Language
@model FlightScheduling.Web.Areas.Administration.Models.Trips.LinkFlightSelectionViewModel
<div class="modal-dialog modal-lg" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4>@FlightsStrings.Link 
                
                @if (Model.DepartureFlight)
                {
                    @FlightsStrings.DepartureFlights
                }
                else
                {
                    @FlightsStrings.ReturningFlights
                }

            </h4>
        </div>
        <div class="modal-body">
            @if (Model.DepartureFlight)
            {
                <p class="alert alert-info"><i class="fa fa-info"></i> @FlightsStrings.DepartureFlightsAlert</p>
            }
            else
            {
                <p class="alert alert-info"><i class="fa fa-info"></i> @FlightsStrings.ReturningFlightsAlert</p>
            }
            
            @Html.Grid(Model.FlightViewModels).Columns(col =>
                {
                    col.For(c => c.FlightNumber).Named(FlightsStrings.FlightNumber);
                    col.For(c => c.AirlineName).Named(FlightsStrings.AirlineName);
                    col.For(c => c.NumberOfPassengers).Named(FlightsStrings.NumberOfPassengers);
                    col.For(c => c.RemainingSeats).Named(FlightsStrings.RemainingSeats);
                    col.For(c => @Html.ActionLink(FlightsStrings.LinkFlight, "LinkFlight", "Trips", new { @ID = c.ID, @TripID = Model.TripID, @DepartureFlight = Model.DepartureFlight }, null)).Named(FlightsStrings.LinkFlight);
                }).Attributes(@class => "table table-hover table-responsive table-condensed", @id => "linkReturingFlights").Empty(CommonStrings.NoFlightsFound)

        </div>
        <div class="modal-footer">

            <button type="button" class="btn btn-default" data-dismiss="modal">@CommonStrings.Close</button>

        </div>
    </div>
</div>

FlightScheduling.Web/Areas/Administration/Views/Trips/_MoveOrder.cshtml
@using Flight.DAL.FlightDB.Methods
@using FlightScheduling.Language
@model FlightScheduling.Web.Areas.Administration.Models.Trips.MoveOrderViewModel

@using (Html.BeginForm("MoveOrder", "Trips", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-validation", id = "form-add-subschool" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => Model.OrderID)

    <div class="modal-dialog modal-lg" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4>@ExpeditionStrings.MoveOrderToOtherTrip</h4>
            </div>
            <div class="modal-body">
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-lg-10 col-md-8 col-sm-6">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Trips, new { @class = "control-label col-md-4" })
                                <div class="col-md-8">
                                    @Html.DropDownListFor(model => model.TripID,new SelectList(Model.Trips.Items,"ID","Name"), new { @class = "form-control chosen-select chosen-rtl" })
                                    @Html.ValidationMessageFor(model => model.Trips)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @*<input type="submit" id="btnSubmit" value="@CommonStrings.SaveAndClose" class="btn btn-default"/>*@
                <button type="button" class="btn btn-default validate-form">
                    <span class="button-text">@CommonStrings.SaveAndClose</span>
                    <div class="white-v"></div>
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">@CommonStrings.Close</button>

            </div>
        </div>
    </div>
}

<script type="text/javascript" src="~/Scripts/Common/validate.form.custom.methods.js"></script>
<script type="text/javascript" src="~/Scripts/chosen/chosen-methods.ajax.js"></script>

FlightScheduling.Web/Areas/Administration/Views/Trips/_TextBoxFlight.cshtml
@model FlightScheduling.Web.Areas.Administration.Models.Trips.FlightDetailsViewModel

@Html.HiddenFor(model => model.ID)
@Html.TextBoxFor(model => model.AssignPassengers, new { @class = "form-control" })
@Html.ValidationMessageFor(model => model.AssignPassengers)

FlightScheduling.Web/Areas/Administration/Views/Trips/_UploadImportTrips.cshtml
@using Flight.DAL.FlightDB.Methods
@using FlightScheduling.Language
@using FlightScheduling.Web.Infrastructure
@model FlightScheduling.Web.Areas.Administration.Models.Trips.ImportTripsViewModel

@using (Html.BeginForm("ImportTrips", "Trips", FormMethod.Post, new { enctype = "multipart/form-data", id = "group-import-participants-form" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg" style="width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>@TripsStrings.ImportTrips</h4>
            </div>
            <div class="modal-body">
                <div class="row" style="margin-bottom: 10px;">
                    <p class="alert alert-info strong">
                        @GroupsStrings.ImportParticipantInstruction
                        <br />
                        <a href="@Url.Action("DownloadFileTemplate", new { FilePath = "ImporttripsTemplate.xlsx", FileName = "ImporttripsTemplate.xlsx" })" class="btn btn-default">@Html.Raw(Html.GetIcon(Icons.Excel, GroupsStrings.DownloadTemplate).ToHtmlString()) @GroupsStrings.DownloadTemplate</a>
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Attachment, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.Attachment, new { type = "file", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Attachment)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default validate-form">
                    <span class="button-text">@CommonStrings.SaveAndClose</span>
                    <div class="white-v"></div>
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">@CommonStrings.Close</button>
            </div>
        </div>
    </div>
}
<script type="text/javascript" src="~/Scripts/Common/jquery.validate.filetypevalidation.js"></script>
<script type="text/javascript" src="~/Scripts/Common/validate.form.custom.methods.js"></script>